sending extras as part of lab

diff --git a/bin/dbwebb-create b/bin/dbwebb-create
--- a/bin/dbwebb-create
+++ b/bin/dbwebb-create
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-VERSION="1.0.0"
+VERSION="1.0.1"
 
 ECHO="printf"
 TMPFILE="/tmp/dbwebb-create$$"
@@ -27,6 +27,7 @@ printUsage()
     $ECHO "\n  lab3      Create laboration 3."
     $ECHO "\n  lab4      Create laboration 4."
     $ECHO "\n  lab5      Create laboration 5."
+    $ECHO "\n  lab6      Create laboration 6."
     $ECHO "\n"
     $ECHO "\nExample:"
     $ECHO "\n"
@@ -45,19 +46,22 @@ createLabJavaScript1()
 {
     LAB="$1"
     WHERE="$TARGET/me/$2/$LAB"
+    HERE="$TARGET/me/$2"
 
     $ECHO "\nCreating $COURSE $LAB."
+
+    # Check if init was run?
+    if [ ! -d "$HERE" ]
+    then
+        echo "\nThe directory '$HERE' is missing.\nDid you run the command bin/dbwebb init?"
+        exit 1
+    fi
 
     # Check if lab is already there
     if [ -f "$WHERE/answer.js" ]
     then
         echo "\nYou already have a lab directory with lab-files.\n$WHERE\nUse it or remove it if you want to create a new lab."
         exit 1
-    else
-        if [ ! -d "$WHERE" ]
-        then
-            mkdir "$WHERE"
-        fi
     fi
 
     # Create the key
@@ -73,6 +77,11 @@ createLabJavaScript1()
     $ECHO "\nanswer.js"
     wget  -qO "$WHERE/answer.js" "$SERVICE/$GET_ANSWER_JS&key=$KEY"
 
+    $ECHO "\nExtras\n"
+    wget  -qO "$WHERE/extra.tar" "$SERVICE/$GET_ANSWER_EXTRA&key=$KEY"
+    tar -xvf "$WHERE/extra.tar" -C "$WHERE"
+    rm -f "$WHERE/extra.tar"
+
     $ECHO "\nYou can find the lab and all files here:\n$WHERE"
 }
 
@@ -85,19 +94,22 @@ createLabPython()
 {
     LAB="$1"
     WHERE="$TARGET/me/$2/$LAB"
+    HERE="$TARGET/me/$2"
 
     $ECHO "\nCreating $COURSE $LAB."
 
+    # Check if init was run?
+    if [ ! -d "$HERE" ]
+    then
+        echo "\nThe directory '$HERE' is missing.\nDid you run the command bin/dbwebb init?"
+        exit 1
+    fi
+
     # Check if lab is already there
-    if [ -d "$WHERE/answer.py" ]
+    if [ -f "$WHERE/answer.py" ]
     then
         echo "\nYou already have a lab directory with lab-files.\n$WHERE\nUse it or remove it if you want to create a new lab."
         exit 1
-    else
-        if [ ! -d "$WHERE" ]
-        then
-            mkdir "$WHERE"
-        fi
     fi
 
     # Create the key
@@ -116,6 +128,11 @@ createLabPython()
 
     $ECHO "\nDbwebb.py"
     wget  -qO "$WHERE/Dbwebb.py" "$SERVICE/$GET_ANSWER_PYDBWEBB&key=$KEY"
+
+    $ECHO "\nExtras\n"
+    wget  -qO "$WHERE/extra.tar" "$SERVICE/$GET_ANSWER_EXTRA&key=$KEY"
+    tar -xvf "$WHERE/extra.tar" -C "$WHERE"
+    rm -f "$WHERE/extra.tar"
 
     $ECHO "\nYou can find the lab and all files here:\n$WHERE"
 }
@@ -187,6 +204,7 @@ then
         lab3) createLabPython "lab3" "kmom04" ;;
         lab4) createLabPython "lab4" "kmom05" ;;
         lab5) createLabPython "lab5" "kmom06" ;;
+        lab6) createLabPython "lab6" "kmom06" ;;
         labtest) createLabPython "labtest" "kmom01" ;;
         *)
             printUsage
